version: '3.4'

services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: my-secret-pw
      MARIADB_DATABASE: cb_db_test
      MARIADB_USER: cb_user 
      MARIADB_PASSWORD: cbpw12345
  brainportal:
    image: brainportal
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
