# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# August 2022: because some developers are not prudent and expose their development CBRAIN
# installations to the wide internet (or they don't even deploy it in production mode?), I have
# removed the hardcoded secret key that was provided in the code base. Instead, I have
# added the special code below to generate a secret that happens to be random enough,
# deterministic and un-guessable. It's based on the filesystem location of the CBRAIN app,
# using the inode numbers of ".", ".." and "../.." . -- Pierre Rioux.

development:
  secret_key_base: <%= Digest::SHA1.hexdigest([".","..","../.."].map { |p| File.stat(p).ino }.join("-")) %>

test:
  secret_key_base: <%= Digest::SHA1.hexdigest([".","..","../.."].map { |p| File.stat(p).ino }.join("-")) %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
